import { MongoClient } from 'mongodb';
import dotenv from 'dotenv';

dotenv.config();

interface ToolSpec {
  id: string;
  name: string;
  slug?: string;
  category: 'Coding' | 'Productivity' | 'Image AI' | 'Video AI' | 'Audio AI' | 'Copywriting' | 'Data & Analytics' | 'Agents';
  pricingType: 'Free' | 'Freemium' | 'Paid' | 'Open Source' | 'Free Trial';
  visits: string; // e.g. "19.4M"
  visitsNum: number;
  rating: number;
  url: string;
  tagline: string;
  desc: string;
  pros: string[];
  cons: string[];
  features: string[];
  deal?: { discount: string; code: string; description: string };
  isFeatured?: boolean;
}

const TOOLS_CATALOG: ToolSpec[] = [
  // ── 1. CODING (15 tools) ──────────────────────────────────────────────────
  {
    id: 'tool-cursor',
    name: 'Cursor AI',
    category: 'Coding',
    pricingType: 'Freemium',
    visits: '19.4M',
    visitsNum: 19400000,
    rating: 4.9,
    url: 'https://cursor.com',
    tagline: 'The AI-first Code Editor built for software engineers to build software faster.',
    desc: 'Intelligent fork of VS Code powered by frontier models with multi-file Composer mode and full codebase indexing.',
    pros: ['VS Code extension compatible', 'Superb multi-file Composer mode', 'Fast Claude 3.7 switching'],
    cons: ['Pro credits consume quickly on large codebases'],
    features: ['Full Monorepo Context Indexing', 'Multi-File Composer Agent', 'Natural Language Terminal Agent'],
    deal: { discount: '14-Day Free Pro', code: 'CURSORDEV', description: 'Get 14 days of unlimited fast Claude Sonnet queries.' },
    isFeatured: true,
  },
  {
    id: 'tool-claude',
    name: 'Claude 3.7',
    category: 'Coding',
    pricingType: 'Freemium',
    visits: '98.2M',
    visitsNum: 98200000,
    rating: 4.9,
    url: 'https://anthropic.com',
    tagline: 'Anthropic’s cutting-edge hybrid reasoning model with Artifacts workspace.',
    desc: 'Frontier reasoning model with hybrid fast/thinking tokens, live React/SVG Artifacts, and 200k context.',
    pros: ['Hybrid reasoning mode', 'Live Artifacts workspace preview', 'Large context window'],
    cons: ['Usage limit throttles on free tier'],
    features: ['Hybrid Fast & Extended Reasoning', 'Live Code & SVG Artifacts', 'Vision & Document Analysis'],
    deal: { discount: '$5 Free API Credits', code: 'CLAUDESTART', description: '$5 free developer API credits.' },
    isFeatured: true,
  },
  {
    id: 'tool-deepseek',
    name: 'DeepSeek-R1',
    category: 'Coding',
    pricingType: 'Open Source',
    visits: '140M',
    visitsNum: 140000000,
    rating: 4.9,
    url: 'https://deepseek.com',
    tagline: 'Open-weight reasoning and coding model matching closed frontier benchmarks.',
    desc: 'Breakthrough open-weights reasoning model matching frontier performance in competitive coding and math.',
    pros: ['100% open weights (MIT license)', 'Unbeatable API price-performance', 'Clear reasoning traces'],
    cons: ['High VRAM requirements to self-host full 671B model'],
    features: ['Open Weights (MIT License)', 'Chain-of-Thought Reasoning', 'Distilled 1.5B to 70B Models'],
    deal: { discount: '100% Free Open Weights', code: 'OPENWEIGHTS', description: 'Free download via Ollama and HuggingFace.' },
    isFeatured: true,
  },
  {
    id: 'tool-github-copilot',
    name: 'GitHub Copilot',
    category: 'Coding',
    pricingType: 'Paid',
    visits: '84M',
    visitsNum: 84000000,
    rating: 4.8,
    url: 'https://github.com/features/copilot',
    tagline: 'The world’s most widely adopted AI developer tool and pair programmer.',
    desc: 'Real-time code completions, pull request summaries, test generation, and CLI terminal assistance in every IDE.',
    pros: ['Native GitHub PR integration', 'Supported in all major IDEs', 'Enterprise compliance'],
    cons: ['Context window smaller than Cursor Composer'],
    features: ['Inline Code Autocomplete', 'Copilot Chat in Editor', 'CLI Command Synthesis'],
    deal: { discount: '30-Day Free Trial', code: 'COPILOTFREE', description: 'Try Copilot 30 days free.' },
  },
  {
    id: 'tool-windsurf',
    name: 'Windsurf by Codeium',
    category: 'Coding',
    pricingType: 'Freemium',
    visits: '14.2M',
    visitsNum: 14200000,
    rating: 4.8,
    url: 'https://codeium.com/windsurf',
    tagline: 'The agentic IDE that keeps developers in continuous creative flow.',
    desc: 'Agentic IDE combining multi-file editing with Cascade AI flows to collaborate on refactors and terminal tasks.',
    pros: ['Cascade flow understands terminal & file states', 'Generous free tier', 'Fast local indexing'],
    cons: ['Newer ecosystem compared to classic VS Code'],
    features: ['Cascade Multi-Turn Agent', 'Deep Repo Context', 'Real-Time Synchronous Awareness'],
    deal: { discount: '20% OFF PRO', code: 'WINDSURF20', description: '20% off annual subscription.' },
  },
  {
    id: 'tool-replit-agent',
    name: 'Replit Agent',
    category: 'Coding',
    pricingType: 'Paid',
    visits: '22.1M',
    visitsNum: 22100000,
    rating: 4.7,
    url: 'https://replit.com',
    tagline: 'Build and deploy full-stack software applications from conversational prompts.',
    desc: 'Designs architecture, installs packages, configures databases, writes code, and deploys live web apps.',
    pros: ['Zero environment setup needed', 'Instant cloud hosting & PostgreSQL', 'Rapid MVP building'],
    cons: ['Requires Replit Core subscription for agent credits'],
    features: ['Autonomous Full-Stack Builder', 'Instant Cloud Deployment', 'Interactive Database Setup'],
  },
  {
    id: 'tool-tabnine',
    name: 'Tabnine',
    category: 'Coding',
    pricingType: 'Freemium',
    visits: '5.8M',
    visitsNum: 5800000,
    rating: 4.6,
    url: 'https://tabnine.com',
    tagline: 'Private, secure AI code completion trained exclusively on permissively licensed code.',
    desc: 'Enterprise code completion assistant with air-gapped deployment and zero data training guarantees.',
    pros: ['Air-gapped and on-prem hosting', 'Permissively licensed code training', 'Zero IP risk'],
    cons: ['Reasoning less advanced than frontier models'],
    features: ['SOC2 & ISO27001 Certified', 'Air-Gapped Deployment', 'Permissive License Guarantee'],
  },
  {
    id: 'tool-v0-vercel',
    name: 'v0 by Vercel',
    category: 'Coding',
    pricingType: 'Freemium',
    visits: '18.4M',
    visitsNum: 18400000,
    rating: 4.9,
    url: 'https://v0.dev',
    tagline: 'Generative UI system that transforms natural language into React and Tailwind components.',
    desc: 'Generates production-ready React components with Tailwind CSS and shadcn/ui styling with live visual preview.',
    pros: ['Clean shadcn/ui React code', 'Instant live visual preview', 'Direct deploy to Vercel'],
    cons: ['Best suited for frontend components rather than deep backend logic'],
    features: ['shadcn/ui Native Generation', 'Real-Time Interactive Preview', 'Vercel Deployment Integration'],
    deal: { discount: 'Free 200 Credits', code: 'V0START', description: '200 free generation credits monthly.' },
  },
  {
    id: 'tool-bolt-new',
    name: 'Bolt.new',
    category: 'Coding',
    pricingType: 'Freemium',
    visits: '16.2M',
    visitsNum: 16200000,
    rating: 4.8,
    url: 'https://bolt.new',
    tagline: 'Prompt, build, and deploy full-stack web applications in-browser via WebContainers.',
    desc: 'In-browser Node.js environment powered by WebContainers that installs npm modules and deploys live web apps.',
    pros: ['Full real Node environment in client browser', 'Fast interactive hot-reloading', 'Direct GitHub export'],
    cons: ['Token limits apply on free tier'],
    features: ['In-Browser WebContainers', 'Full Stack npm Execution', 'One-Click Netlify Deploy'],
  },
  {
    id: 'tool-lovable',
    name: 'Lovable',
    category: 'Coding',
    pricingType: 'Freemium',
    visits: '8.9M',
    visitsNum: 8900000,
    rating: 4.8,
    url: 'https://lovable.dev',
    tagline: 'The AI software engineer for building production-grade web applications from text.',
    desc: 'Transforms product briefs into fully responsive web applications with Supabase databases and modern UX.',
    pros: ['Aesthetic UI out of the box', 'Supabase database integration', 'Exportable clean codebase'],
    cons: ['Credit quota requires upgrade for continuous development'],
    features: ['Supabase Integration', 'Full Design System Cohesion', 'Instant Responsive Preview'],
  },
  {
    id: 'tool-sourcegraph-cody',
    name: 'Sourcegraph Cody',
    category: 'Coding',
    pricingType: 'Freemium',
    visits: '4.1M',
    visitsNum: 4100000,
    rating: 4.7,
    url: 'https://sourcegraph.com/cody',
    tagline: 'AI coding assistant powered by multi-repo code graph search and context.',
    desc: 'Leverages Sourcegraph code graph intelligence to understand entire monorepos and internal company libraries.',
    pros: ['Superior monorepo indexing', 'Choice of underlying frontier LLMs', 'Strict privacy guarantees'],
    cons: ['Interface slightly more complex for novice programmers'],
    features: ['Code Graph Semantic Index', 'Multi-Repo Architecture Search', 'Unit Test Synthesizer'],
  },
  {
    id: 'tool-amazon-q-dev',
    name: 'Amazon Q Developer',
    category: 'Coding',
    pricingType: 'Freemium',
    visits: '12.4M',
    visitsNum: 12400000,
    rating: 4.6,
    url: 'https://aws.amazon.com/q/developer',
    tagline: 'Generative AI assistant for software development, cloud infrastructure, and migrations.',
    desc: 'Accelerates application development, security scanning, Java upgrades, and AWS cloud architecture configurations.',
    pros: ['Automated Java runtime upgrade transforms', 'Direct AWS CLI and CloudFormation', 'Vulnerability scanning'],
    cons: ['Tightly coupled with AWS ecosystem'],
    features: ['Automated Code Transformation', 'AWS Security Vulnerability Fixer', 'Cloud Architecture Helper'],
  },
  {
    id: 'tool-aider',
    name: 'Aider',
    category: 'Coding',
    pricingType: 'Open Source',
    visits: '3.2M',
    visitsNum: 3200000,
    rating: 4.9,
    url: 'https://aider.chat',
    tagline: 'AI pair programming in your terminal with automated git commit checkpoints.',
    desc: 'Open-source command-line tool that lets you pair program with LLMs in your terminal with automatic git commits.',
    pros: ['Automatic git commit with sensible commit messages', 'Supports local models like DeepSeek-R1', 'Zero vendor lock-in'],
    cons: ['Pure CLI experience without graphical UI'],
    features: ['Git Auto-Commits', 'Repository Map AST Parsing', 'Voice Coding Support'],
  },
  {
    id: 'tool-qodo',
    name: 'Qodo',
    category: 'Coding',
    pricingType: 'Freemium',
    visits: '2.8M',
    visitsNum: 2800000,
    rating: 4.7,
    url: 'https://qodo.ai',
    tagline: 'Quality-first generative AI code integrity, test generation, and review platform.',
    desc: 'Helps development teams write meaningful unit tests, identify edge-case bugs, and review PRs automatically.',
    pros: ['Generates comprehensive test suites with mocking', 'Detects edge cases other LLMs miss', 'PR review agent integration'],
    cons: ['Focused heavily on testing rather than rapid prototyping'],
    features: ['Test-Driven Development Agent', 'Edge-Case Analysis', 'Automated PR Reviewer'],
  },
  {
    id: 'tool-continue-dev',
    name: 'Continue.dev',
    category: 'Coding',
    pricingType: 'Open Source',
    visits: '2.6M',
    visitsNum: 2600000,
    rating: 4.8,
    url: 'https://continue.dev',
    tagline: 'The leading open-source AI code assistant for VS Code and JetBrains.',
    desc: 'Modular open-source autopilot that connects any custom LLM (Ollama, LM Studio) to create personalized coding flows.',
    pros: ['100% open-source and local privacy safe', 'Swap models freely without subscription costs', 'Active community plugins'],
    cons: ['Requires basic configuration compared to turnkey SaaS products'],
    features: ['Local Model Integration (Ollama)', 'Custom Slash Commands', 'Codebase Embeddings'],
  },

  // ── 2. PRODUCTIVITY (15 tools) ────────────────────────────────────────────
  {
    id: 'tool-chatgpt',
    name: 'ChatGPT',
    category: 'Productivity',
    pricingType: 'Freemium',
    visits: '3.7B',
    visitsNum: 3700000000,
    rating: 4.9,
    url: 'https://chatgpt.com',
    tagline: 'The world’s leading conversational AI system for knowledge, coding, and reasoning.',
    desc: 'Access to OpenAI frontier models with web browsing, code execution, image creation, and custom GPTs.',
    pros: ['Universal frontier capabilities', 'Rich Custom GPT store', 'Advanced Data Analysis python engine'],
    cons: ['Pro/Plus features require subscription'],
    features: ['Web Search Grounding', 'Python Code Interpreter', 'DALL-E 3 Image Generation'],
    deal: { discount: 'Free Access', code: 'GPTFREE', description: 'Free tier with GPT-4o access.' },
    isFeatured: true,
  },
  {
    id: 'tool-perplexity',
    name: 'Perplexity AI',
    category: 'Productivity',
    pricingType: 'Freemium',
    visits: '95.4M',
    visitsNum: 95400000,
    rating: 4.8,
    url: 'https://perplexity.ai',
    tagline: 'Where knowledge begins. Conversational answer engine with direct citations.',
    desc: 'Real-time multi-source web crawling with frontier LLM synthesis to deliver cited, verifiable research summaries.',
    pros: ['Clickable footnote citations on every claim', 'Pro Search multi-step query loops', 'Collections feature for research'],
    cons: ['Pro subscription required for deep multi-step loops'],
    features: ['Citations on Every Paragraph', 'Pro Search Reasoning Loops', 'Academic & Reddit Source Focus'],
    deal: { discount: '$10 OFF Pro', code: 'PERPLEXFLUX', description: '$10 off first month of Perplexity Pro.' },
    isFeatured: true,
  },
  {
    id: 'tool-notion-ai',
    name: 'Notion AI',
    category: 'Productivity',
    pricingType: 'Paid',
    visits: '165M',
    visitsNum: 165000000,
    rating: 4.8,
    url: 'https://notion.so',
    tagline: 'Connected AI workspace that searches across all your company docs, notes, and tasks.',
    desc: 'Transforms your workspace into an intelligent knowledge graph with database autofills and meeting summaries.',
    pros: ['Queries across entire workspace database', 'Autofills relational tables', 'Clean minimalist UI'],
    cons: ['Requires $10/user/mo add-on'],
    features: ['Connected Workspace Q&A', 'AI Database Auto-Fill', 'Action Item Summarizer'],
  },
  {
    id: 'tool-microsoft-copilot',
    name: 'Microsoft Copilot',
    category: 'Productivity',
    pricingType: 'Freemium',
    visits: '98M',
    visitsNum: 98000000,
    rating: 4.7,
    url: 'https://copilot.microsoft.com',
    tagline: 'Everyday AI companion integrated across Windows, Microsoft 365, and Edge.',
    desc: 'Connects GPT-4o intelligence to emails, Excel sheets, PowerPoint decks, and Windows OS workflows.',
    pros: ['Deep Office 365 integration', 'Enterprise data protection', 'Free web version'],
    cons: ['Excel formulas can struggle on complex nested arrays'],
    features: ['Microsoft 365 App Integration', 'Web Search Grounding', 'PowerPoint Slide Generator'],
  },
  {
    id: 'tool-google-gemini',
    name: 'Google Gemini',
    category: 'Productivity',
    pricingType: 'Freemium',
    visits: '310M',
    visitsNum: 310000000,
    rating: 4.8,
    url: 'https://gemini.google.com',
    tagline: 'Google’s multimodal frontier AI with a massive 2M token context window.',
    desc: 'Google 1.5 Pro and 2.0 models with deep integration across Docs, Gmail, Drive, and YouTube.',
    pros: ['2 Million token context window', 'Native YouTube and Drive search', 'Fast real-time responses'],
    cons: ['Safety filters can be cautious'],
    features: ['2 Million Token Context', 'Google Workspace Integration', 'Multimodal Audio & Video'],
  },
  {
    id: 'tool-otter-ai',
    name: 'Otter.ai',
    category: 'Productivity',
    pricingType: 'Freemium',
    visits: '14.8M',
    visitsNum: 14800000,
    rating: 4.7,
    url: 'https://otter.ai',
    tagline: 'Automated AI meeting assistant for real-time transcription, summaries, and action items.',
    desc: 'Joins Zoom, Meet, and Teams calls automatically to record, transcribe, capture slides, and generate action items.',
    pros: ['Auto-joins calendar meetings', 'Captures presentation slides automatically', 'Searchable audio timeline'],
    cons: ['Free plan has monthly minutes limit'],
    features: ['Automated Meeting Bot', 'Real-Time Slide Capture', 'AI Chat With Transcript'],
  },
  {
    id: 'tool-granola',
    name: 'Granola',
    category: 'Productivity',
    pricingType: 'Freemium',
    visits: '3.1M',
    visitsNum: 3100000,
    rating: 4.9,
    url: 'https://granola.so',
    tagline: 'The AI notepad for people who already like taking notes in meetings.',
    desc: 'Sits discreetly on your desktop during meetings, transcribes audio without a bot, and enhances notes into memos.',
    pros: ['No awkward bot joining the call', 'Blends human thoughts with AI transcript', 'Superb aesthetics'],
    cons: ['Currently macOS only'],
    features: ['Bot-Free Audio Transcription', 'Note-Enhancement Engine', 'Shareable Executive Briefs'],
  },
  {
    id: 'tool-fireflies-ai',
    name: 'Fireflies.ai',
    category: 'Productivity',
    pricingType: 'Freemium',
    visits: '7.6M',
    visitsNum: 7600000,
    rating: 4.7,
    url: 'https://fireflies.ai',
    tagline: 'AI voice assistant that transcribes, summarizes, and analyzes team voice conversations.',
    desc: 'Records and transcribes meetings with sentiment analysis, speaker analytics, and automated CRM updates.',
    pros: ['Automates HubSpot and Salesforce CRM logging', 'Conversation intelligence analytics', 'Supports 60+ languages'],
    cons: ['Bot presence requires meeting participant notice'],
    features: ['CRM Auto-Logging', 'Sentiment & Talk-Time Analytics', 'Smart Search Filters'],
  },
  {
    id: 'tool-raycast-ai',
    name: 'Raycast AI',
    category: 'Productivity',
    pricingType: 'Freemium',
    visits: '6.4M',
    visitsNum: 6400000,
    rating: 4.9,
    url: 'https://raycast.com',
    tagline: 'Blazing fast AI launcher for Mac that controls your workflow with hotkeys.',
    desc: 'Integrates frontier models directly into the macOS system launcher with sub-millisecond hotkey queries.',
    pros: ['Sub-millisecond keyboard workflow', 'Switch models with one click', 'Huge community extension store'],
    cons: ['Full AI features require Pro subscription'],
    features: ['Global Keyboard Shortcut Launcher', 'Multi-Model Switcher', 'Custom AI Prompt Commands'],
  },
  {
    id: 'tool-superhuman-ai',
    name: 'Superhuman AI',
    category: 'Productivity',
    pricingType: 'Paid',
    visits: '4.8M',
    visitsNum: 4800000,
    rating: 4.8,
    url: 'https://superhuman.com',
    tagline: 'The fastest email experience ever made, now supercharged with generative AI.',
    desc: 'Drafts replies in your voice from bullet points, triages inboxes with split categories, and extracts action items.',
    pros: ['Cuts email processing time by half', 'Matches your tone and history', 'Blazing speed'],
    cons: ['Premium price point'],
    features: ['Voice Mimicking Email Drafts', '1-Line Reply Expander', 'Automated Meeting Scheduling'],
  },
  {
    id: 'tool-heptabase',
    name: 'Heptabase',
    category: 'Productivity',
    pricingType: 'Paid',
    visits: '2.9M',
    visitsNum: 2900000,
    rating: 4.8,
    url: 'https://heptabase.com',
    tagline: 'Visual whiteboard note-taking tool that helps researchers make sense of complex topics.',
    desc: 'Combines visual mind mapping with modular markdown cards, PDF annotation, and AI concept synthesis.',
    pros: ['Infinite canvas spatial layout', 'Seamless PDF highlight conversion', 'Offline-first database'],
    cons: ['Paid-only model'],
    features: ['Visual Whiteboard Mapping', 'PDF Annotation Card Sync', 'Bi-Directional Wiki Linking'],
  },
  {
    id: 'tool-taskade',
    name: 'Taskade',
    category: 'Productivity',
    pricingType: 'Freemium',
    visits: '4.3M',
    visitsNum: 4300000,
    rating: 4.7,
    url: 'https://taskade.com',
    tagline: 'Build AI agent teams that automate workflows, manage projects, and draft content.',
    desc: 'Productivity suite featuring customizable autonomous AI agents collaborating on task delegation and planning.',
    pros: ['Deploy multi-agent task teams', 'Real-time collaborative workspaces', 'Generous free tier'],
    cons: ['Feature-dense interface'],
    features: ['Autonomous Agent Workflows', 'Dynamic Mind Map to Task Views', 'AI Chat With Docs'],
  },
  {
    id: 'tool-limitless-ai',
    name: 'Limitless',
    category: 'Productivity',
    pricingType: 'Freemium',
    visits: '3.8M',
    visitsNum: 3800000,
    rating: 4.7,
    url: 'https://limitless.ai',
    tagline: 'Personalized AI with limitless memory that records everything you see, hear, and say.',
    desc: 'Captures conversations from meetings, browser tabs, and real-world audio to recall details and synthesize work.',
    pros: ['Spoken conversation recall', 'Wearable Pendant hardware integration', 'Encrypted cloud'],
    cons: ['Hardware device sold separately'],
    features: ['Continuous Audio Recall', 'Automated Prep for Calendar Events', 'Wearable Hardware Sync'],
  },
  {
    id: 'tool-fathom',
    name: 'Fathom',
    category: 'Productivity',
    pricingType: 'Free',
    visits: '6.2M',
    visitsNum: 6200000,
    rating: 4.9,
    url: 'https://fathom.video',
    tagline: 'Free AI meeting recorder that eliminates manual note-taking on Zoom and Teams.',
    desc: 'Free AI meeting assistant that records, transcribes, highlights crucial moments, and generates action summaries.',
    pros: ['100% free transcription for individuals', 'One-click timestamp bookmarking', 'Direct CRM sync'],
    cons: ['Team features require paid upgrade'],
    features: ['Free Unlimited Recording', 'One-Click Meeting Bookmarks', 'CRM Sync Automation'],
  },
  {
    id: 'tool-mem-ai',
    name: 'Mem AI',
    category: 'Productivity',
    pricingType: 'Freemium',
    visits: '2.2M',
    visitsNum: 2200000,
    rating: 4.6,
    url: 'https://mem.ai',
    tagline: 'Self-organizing workspace that automatically connects your notes, links, and ideas.',
    desc: 'Removes manual folder categorization by using AI to dynamically link related notes based on semantic relevance.',
    pros: ['Zero need for manual tags or folders', 'Fast smart search', 'Clean mobile quick-capture'],
    cons: ['Search accuracy depends on note volume'],
    features: ['Self-Organizing Smart Collections', 'Contextual Knowledge Assistant', 'Zapier Automation'],
  },

  // ── 3. IMAGE AI (15 tools) ────────────────────────────────────────────────
  {
    id: 'tool-midjourney',
    name: 'Midjourney v6',
    category: 'Image AI',
    pricingType: 'Paid',
    visits: '34.5M',
    visitsNum: 34500000,
    rating: 4.9,
    url: 'https://midjourney.com',
    tagline: 'The gold standard in artistic AI image synthesis and aesthetic visual generation.',
    desc: 'Leading text-to-image generator known for exquisite artistic style, photorealistic textures, and character consistency.',
    pros: ['Unrivaled aesthetic quality', 'Realistic skin and lighting', 'Web canvas editor'],
    cons: ['No free trial tier'],
    features: ['Style Tuner & Reference Codes', 'Vary Region Inpainting', 'Pan & Zoom Canvas Expansion'],
    isFeatured: true,
  },
  {
    id: 'tool-lumina-ai',
    name: 'Lumina AI',
    category: 'Image AI',
    pricingType: 'Freemium',
    visits: '12.8M',
    visitsNum: 12800000,
    rating: 4.8,
    url: 'https://lumina.ai',
    tagline: 'Next-generation image upscaling, generative inpainting, and photo enhancement.',
    desc: 'AI studio specializing in 8K neural upscaling, facial restoration, and background generative expansion.',
    pros: ['Fast 8K generation', 'Lossless face enhancement', 'Batch processing'],
    cons: ['High resolution exports consume credits'],
    features: ['8K Generative Upscaler', 'Facial Texture Reconstruction', 'AI Lighting Relight'],
    deal: { discount: '30% OFF Annual', code: 'LUMINA30', description: '30% off Pro annual subscription.' },
    isFeatured: true,
  },
  {
    id: 'tool-flux-1',
    name: 'Flux.1 by Black Forest Labs',
    category: 'Image AI',
    pricingType: 'Open Source',
    visits: '18.6M',
    visitsNum: 18600000,
    rating: 4.9,
    url: 'https://blackforestlabs.ai',
    tagline: 'State-of-the-art open weights image foundation model from the creators of Stable Diffusion.',
    desc: 'Unprecedented prompt following, anatomical precision, and typography synthesis with open weights.',
    pros: ['Exceptional typography and text rendering', 'Realistic human hands and anatomy', 'Open weights available'],
    cons: ['Schnell model faster than Dev/Pro but slightly lower fidelity'],
    features: ['Flawless Text & Typography Synthesis', 'Open Weights Architecture', '12B Parameter Flow Transformer'],
    deal: { discount: 'Free Open Weights', code: 'FLUXOPEN', description: 'Open weights available on HuggingFace.' },
  },
  {
    id: 'tool-dalle-3',
    name: 'DALL-E 3',
    category: 'Image AI',
    pricingType: 'Freemium',
    visits: '45M',
    visitsNum: 45000000,
    rating: 4.8,
    url: 'https://openai.com/dall-e-3',
    tagline: 'OpenAI’s native image generator with incredible natural language prompt fidelity.',
    desc: 'Translates nuanced requests into images directly within ChatGPT without needing complex prompt syntax.',
    pros: ['Understands complex descriptive paragraphs', 'Integrated into ChatGPT', 'Great text rendering in images'],
    cons: ['Less photorealistic camera grain than Midjourney'],
    features: ['Conversational Inpainting', 'Direct ChatGPT Integration', 'Safe Copyright Protection'],
  },
  {
    id: 'tool-stable-diffusion-3',
    name: 'Stable Diffusion 3.5',
    category: 'Image AI',
    pricingType: 'Open Source',
    visits: '28M',
    visitsNum: 28000000,
    rating: 4.8,
    url: 'https://stability.ai',
    tagline: 'Open image generation model with multi-modal diffusion transformer architecture.',
    desc: 'Stability AI flagship model running on consumer hardware with customizable LoRAs and ControlNet.',
    pros: ['Runs locally on private GPUs', 'Huge community LoRA ecosystem', 'Commercial permissive license'],
    cons: ['Requires technical setup via ComfyUI or WebUI'],
    features: ['MMDiT Architecture', 'ControlNet & LoRA Compatibility', 'Local Private Inference'],
  },
  {
    id: 'tool-leonardo-ai',
    name: 'Leonardo.ai',
    category: 'Image AI',
    pricingType: 'Freemium',
    visits: '19.2M',
    visitsNum: 19200000,
    rating: 4.8,
    url: 'https://leonardo.ai',
    tagline: 'Generative creative suite for digital artists, game concept art, and marketing designers.',
    desc: 'Full-featured creative canvas with real-time AI canvas painting, custom model training, and 3D texture synthesis.',
    pros: ['Real-time canvas generation', 'Train custom models on your art style', 'Generous daily free tokens'],
    cons: ['Canvas tools have a learning curve'],
    features: ['Realtime Canvas AI Painting', 'Custom Model Training', 'Universal Upscaler'],
  },
  {
    id: 'tool-adobe-firefly',
    name: 'Adobe Firefly',
    category: 'Image AI',
    pricingType: 'Freemium',
    visits: '22.5M',
    visitsNum: 22500000,
    rating: 4.7,
    url: 'https://firefly.adobe.com',
    tagline: 'Commercially safe generative AI built directly into Photoshop, Illustrator, and Premiere.',
    desc: 'Trained exclusively on licensed Adobe Stock images, offering enterprise indemnification and seamless Creative Cloud sync.',
    pros: ['100% commercially safe with IP indemnity', 'Native Generative Fill in Photoshop', 'Vector artwork generation'],
    cons: ['Stylistic output can feel safe and corporate'],
    features: ['Generative Fill & Expand in Photoshop', 'Text-to-Vector in Illustrator', 'Commercial Safety Guarantee'],
  },
  {
    id: 'tool-ideogram',
    name: 'Ideogram 2.0',
    category: 'Image AI',
    pricingType: 'Freemium',
    visits: '15.4M',
    visitsNum: 15400000,
    rating: 4.9,
    url: 'https://ideogram.ai',
    tagline: 'The undisputed champion of typography and clear graphic design generation.',
    desc: 'Renders crisp text on t-shirts, posters, logos, and digital ads with graphic design color palettes.',
    pros: ['Best-in-class text spelling in images', 'Superb graphic design & logo aesthetics', 'Generous free daily tier'],
    cons: ['Photorealism slightly behind Midjourney on portraits'],
    features: ['Graphic Design & Poster Engine', 'Flawless Multi-Word Typography', 'Color Palette Control'],
    deal: { discount: '20% OFF Pro', code: 'IDEOPRO20', description: '20% off yearly subscription.' },
  },
  {
    id: 'tool-recraft',
    name: 'Recraft',
    category: 'Image AI',
    pricingType: 'Freemium',
    visits: '8.2M',
    visitsNum: 8200000,
    rating: 4.8,
    url: 'https://recraft.ai',
    tagline: 'AI design canvas for generating brand vectors, 3D icons, and brand illustrations.',
    desc: 'Generates editable SVG vectors and illustrations that adhere strictly to your brand color palette.',
    pros: ['Direct SVG vector export', 'Strict brand palette consistency', 'Infinite design canvas'],
    cons: ['Specialized in design graphics rather than photography'],
    features: ['Infinite Vector Canvas', 'Brand Palette Lock', 'Editable SVG Generation'],
  },
  {
    id: 'tool-photoroom',
    name: 'Photoroom',
    category: 'Image AI',
    pricingType: 'Freemium',
    visits: '16.8M',
    visitsNum: 16800000,
    rating: 4.8,
    url: 'https://photoroom.com',
    tagline: 'AI photo editor for e-commerce product photography, background removal, and retouching.',
    desc: 'Instantly removes backgrounds and generates realistic commercial studio lighting for online stores.',
    pros: ['Fast background removal', 'Instant studio product photography', 'Batch editing on mobile'],
    cons: ['High-res exports require paid tier'],
    features: ['Studio Background Synthesizer', 'Batch E-Commerce Retouching', 'Automatic Shadows & Lighting'],
  },
  {
    id: 'tool-krea-ai',
    name: 'Krea AI',
    category: 'Image AI',
    pricingType: 'Freemium',
    visits: '7.4M',
    visitsNum: 7400000,
    rating: 4.8,
    url: 'https://krea.ai',
    tagline: 'Real-time generative AI canvas and camera enhancer for instant creative direction.',
    desc: 'Draw rough shapes on a canvas and watch photorealistic AI renderings generate in real-time at 30 FPS.',
    pros: ['Sub-100ms real-time rendering', 'AI video generation tools', 'Screen-share canvas mode'],
    cons: ['Fast compute requires GPU credits'],
    features: ['Real-Time 30FPS Canvas', 'AI Video Keyframing', 'AI Screen Enhancer'],
  },
  {
    id: 'tool-magnific-ai',
    name: 'Magnific AI',
    category: 'Image AI',
    pricingType: 'Paid',
    visits: '5.2M',
    visitsNum: 5200000,
    rating: 4.9,
    url: 'https://magnific.ai',
    tagline: 'The world’s most advanced AI upscaler and detail hallucinater for professional creators.',
    desc: 'Transforms low-res renders into ultra-detailed 16K masterworks by hallucinating realistic skin and textures.',
    pros: ['Breathtaking detail generation', 'Controllable hallucination slider', 'Supports up to 16K resolution'],
    cons: ['High subscription price point'],
    features: ['16K Super-Resolution Upscaling', 'Hallucination & Creativity Sliders', 'Cinematic Texture Synthesis'],
  },
  {
    id: 'tool-clipdrop',
    name: 'Clipdrop by Jasper',
    category: 'Image AI',
    pricingType: 'Freemium',
    visits: '9.1M',
    visitsNum: 9100000,
    rating: 4.7,
    url: 'https://clipdrop.co',
    tagline: 'Ecosystem of AI imaging apps for cleanup, relighting, and background swapping.',
    desc: 'One-click object cleanup, background removal, text removal, and virtual studio relighting.',
    pros: ['Easy single-purpose tools', 'Studio Relight feature is magic', 'Fast web performance'],
    cons: ['Free exports capped at standard resolution'],
    features: ['AI Relight Studio Lighting', 'One-Click Object Cleanup', 'Image Uncrop Extension'],
  },
  {
    id: 'tool-freepik-pikaso',
    name: 'Freepik Pikaso',
    category: 'Image AI',
    pricingType: 'Freemium',
    visits: '11.5M',
    visitsNum: 11500000,
    rating: 4.7,
    url: 'https://freepik.com/pikaso',
    tagline: 'Real-time sketch to image AI generator with millions of design assets.',
    desc: 'Draw or combine icons and watch AI produce finished illustrations instantly with Freepik asset integration.',
    pros: ['Real-time sketch rendering', 'Integrated with Freepik library', 'Webcam drawing inputs'],
    cons: ['Requires Freepik Premium for full exports'],
    features: ['Real-Time Sketch Generator', 'Freepik Asset Integration', 'Webcam Drawing Input'],
  },
  {
    id: 'tool-playground-ai',
    name: 'Playground AI',
    category: 'Image AI',
    pricingType: 'Freemium',
    visits: '6.8M',
    visitsNum: 6800000,
    rating: 4.7,
    url: 'https://playground.com',
    tagline: 'Free-to-use AI image creator with infinite canvas and mixed image editing.',
    desc: 'Combines multiple images on an infinite canvas, removes background items, and applies style filters.',
    pros: ['Generous daily free image quota', 'Mixed canvas composition', 'Beginner friendly filters'],
    cons: ['Queue times longer during peak hours'],
    features: ['Infinite Mixed Canvas', 'Smart Style Presets', 'Inpainting & Outpainting'],
  },

  // ── 4. VIDEO AI (15 tools) ────────────────────────────────────────────────
  {
    id: 'tool-vidgenix',
    name: 'VidGenix Studio',
    category: 'Video AI',
    pricingType: 'Freemium',
    visits: '14.6M',
    visitsNum: 14600000,
    rating: 4.8,
    url: 'https://vidgenix.ai',
    tagline: 'Generate cinematic 4K video clips, realistic lip-sync, and b-roll from text prompts.',
    desc: 'Produces cinematic 4K clips, camera motion controls, and studio lip-sync from text scripts.',
    pros: ['Cinematic 4K resolution output', 'Accurate lip-sync dubbing', 'Dynamic camera motions'],
    cons: ['Rendering requires compute queue credits'],
    features: ['Text to 4K Video Clips', 'Realistic Lip-Sync Dubbing', 'Camera Motion Directing'],
    deal: { discount: '40% OFF Monthly', code: 'VIDGENIX40', description: '40% off Director plan.' },
    isFeatured: true,
  },
  {
    id: 'tool-runway-gen3',
    name: 'Runway Gen-3 Alpha',
    category: 'Video AI',
    pricingType: 'Freemium',
    visits: '24.8M',
    visitsNum: 24800000,
    rating: 4.9,
    url: 'https://runwayml.com',
    tagline: 'Pioneering generative video model for photorealistic motion, lighting, and cinematic effects.',
    desc: 'Hollywood-grade text-to-video and image-to-video generation with camera control and Motion Brush.',
    pros: ['Photorealistic lighting and human motion', 'Director camera controls', 'Motion Brush keyframing'],
    cons: ['Video generations consume credits rapidly'],
    features: ['Gen-3 Alpha Photorealistic Physics', 'Camera Directional Controls', 'Motion Brush Masking'],
    deal: { discount: '20% OFF ANNUAL', code: 'RUNWAY20', description: '20% off annual subscription.' },
  },
  {
    id: 'tool-luma-dream-machine',
    name: 'Luma Dream Machine',
    category: 'Video AI',
    pricingType: 'Freemium',
    visits: '18.2M',
    visitsNum: 18200000,
    rating: 4.8,
    url: 'https://lumalabs.ai/dream-machine',
    tagline: 'Next-generation video foundation model with accurate physics and spatial consistency.',
    desc: 'Generates high-fidelity 5-second video shots from images or text with spatial realism and smooth pans.',
    pros: ['Great camera pans and smooth zooms', 'Consistent spatial perspective', 'Fast rendering pipeline'],
    cons: ['Video length limited to 5-second blocks'],
    features: ['Spatial Perspective Physics', 'Image-to-Video Transformation', 'Camera Movement Control'],
  },
  {
    id: 'tool-kling-ai',
    name: 'Kling AI',
    category: 'Video AI',
    pricingType: 'Freemium',
    visits: '22.0M',
    visitsNum: 22000000,
    rating: 4.9,
    url: 'https://klingai.com',
    tagline: 'Frontier AI video generator capable of generating 1080p clips up to 2 minutes long.',
    desc: 'Excels at complex human actions, cooking motions, physical interactions, and long video duration.',
    pros: ['Can generate up to 2-minute clips', 'Superb complex physics and liquid simulations', 'High prompt accuracy'],
    cons: ['Free queue can experience peak delays'],
    features: ['1080p Extended Video Generation', 'Realistic Fluid & Physics Motion', 'Complex Action Sequences'],
  },
  {
    id: 'tool-pika-art',
    name: 'Pika 2.0',
    category: 'Video AI',
    pricingType: 'Freemium',
    visits: '12.4M',
    visitsNum: 12400000,
    rating: 4.7,
    url: 'https://pika.art',
    tagline: 'Creative video generation platform with Pikaffects (inflate, melt, crush, explode).',
    desc: 'Brings concepts to life with text-to-video, inpainting, and fun physical Pikaffects.',
    pros: ['Unique viral Pikaffects (melt, squish, crush)', 'Lip sync integration', 'Sound effect audio synthesis'],
    cons: ['Motion realism sometimes stylized'],
    features: ['Pikaffects Physics FX', 'Audio & Sound Effects Sync', 'Canvas Expansion & Inpaint'],
  },
  {
    id: 'tool-heygen',
    name: 'HeyGen',
    category: 'Video AI',
    pricingType: 'Freemium',
    visits: '16.5M',
    visitsNum: 16500000,
    rating: 4.9,
    url: 'https://heygen.com',
    tagline: 'AI video generation platform for corporate avatars, multi-lingual video translation, and sales outreach.',
    desc: 'Creates photorealistic digital twin avatars that speak scripts with perfect natural lip-sync in 175+ languages.',
    pros: ['Industry-best avatar realism', 'Automatic video translation with voice cloning', 'Fast video rendering'],
    cons: ['Custom avatar creation requires verification recording'],
    features: ['Photo & Studio Video Avatars', 'Multi-Lingual Video Translation', 'API Automation Connectors'],
    deal: { discount: 'Free Demo Video', code: 'HEYGENFREE', description: 'Create 1 free AI avatar video.' },
  },
  {
    id: 'tool-sora-openai',
    name: 'OpenAI Sora',
    category: 'Video AI',
    pricingType: 'Paid',
    visits: '38.0M',
    visitsNum: 38000000,
    rating: 4.9,
    url: 'https://sora.com',
    tagline: 'OpenAI’s world simulator video model that generates 1080p cinematic scenes from text.',
    desc: 'Understands how objects exist in the physical world to generate scenes with complex camera motion and multiple characters.',
    pros: ['Incredible cinematic quality', 'Physical world simulation', 'Seamless video looping'],
    cons: ['Requires ChatGPT Plus or Pro subscription'],
    features: ['Physical World Simulation', '1080p Resolution Generation', 'Multi-Angle Camera Consistency'],
  },
  {
    id: 'tool-synthesia',
    name: 'Synthesia',
    category: 'Video AI',
    pricingType: 'Paid',
    visits: '11.8M',
    visitsNum: 11800000,
    rating: 4.8,
    url: 'https://synthesia.io',
    tagline: 'Enterprise AI video creation platform with 160+ AI avatars and 130+ languages.',
    desc: 'Empowers HR, L&D, and sales teams to create corporate training videos from text without cameras or microphones.',
    pros: ['Enterprise security & SOC2', '160+ diverse avatars', 'Screen recorder integration'],
    cons: ['Paid-only plans'],
    features: ['Enterprise Video Avatars', '130+ Global Languages', 'Interactive Video Quizzes'],
  },
  {
    id: 'tool-hailuo-ai',
    name: 'Hailuo AI (MiniMax)',
    category: 'Video AI',
    pricingType: 'Freemium',
    visits: '14.1M',
    visitsNum: 14100000,
    rating: 4.8,
    url: 'https://hailuoai.video',
    tagline: 'Breakthrough video foundation model with cinematic camera dynamics and human expressions.',
    desc: 'Generates dramatic cinematic scenes with realistic facial emotion and smooth physical motions.',
    pros: ['Exceptional emotional human expressions', 'Cinematic depth of field', 'Fast rendering speed'],
    cons: ['Duration capped at 6 seconds per generation'],
    features: ['Expressive Facial Motion', 'Cinematic Depth of Field', 'Text & Image Input Modes'],
  },
  {
    id: 'tool-invideo-ai',
    name: 'InVideo AI',
    category: 'Video AI',
    pricingType: 'Freemium',
    visits: '15.2M',
    visitsNum: 15200000,
    rating: 4.7,
    url: 'https://invideo.io',
    tagline: 'Type in any topic and InVideo generates a complete video with script, stock clips, voiceover, and captions.',
    desc: 'Turns simple text prompts into full YouTube Shorts, TikToks, and long-form YouTube videos ready to publish.',
    pros: ['Generates full complete videos automatically', 'Humanlike voiceover included', 'Huge stock footage library'],
    cons: ['Voiceover tone can sound slightly repetitive without custom editing'],
    features: ['End-to-End Video Generator', 'Automated Subtitles & Captions', 'iStock Media Library Access'],
  },
  {
    id: 'tool-captions-ai',
    name: 'Captions AI',
    category: 'Video AI',
    pricingType: 'Paid',
    visits: '8.6M',
    visitsNum: 8600000,
    rating: 4.8,
    url: 'https://captions.ai',
    tagline: 'Creative studio for talking videos with AI Eye Contact, audio denoiser, and dynamic captions.',
    desc: 'Everything creators need to edit talking-head videos with viral animated subtitles and AI eye contact correction.',
    pros: ['Eye contact fix looks completely natural', 'Viral animated subtitle presets', 'AI dubbing with lip sync'],
    cons: ['Requires mobile or desktop paid subscription'],
    features: ['AI Eye Contact Correction', 'Viral Animated Captions', 'Studio Sound Cleanup'],
  },
  {
    id: 'tool-descript',
    name: 'Descript',
    category: 'Video AI',
    pricingType: 'Freemium',
    visits: '10.4M',
    visitsNum: 10400000,
    rating: 4.8,
    url: 'https://descript.com',
    tagline: 'All-in-one video and podcast editing that feels as simple as editing a Google Doc.',
    desc: 'Edit video by editing text. Delete filler words, clone your voice with Overdub, and export multi-cam tracks.',
    pros: ['Text-based video editing paradigm', 'Removes "um" and "uh" filler words in 1 click', 'Studio Sound audio enhancement'],
    cons: ['Cloud processing can slow down on massive 4K footage'],
    features: ['Text-Based Timeline Editing', 'Filler Word Remover', 'Studio Sound AI Enhancement'],
  },
  {
    id: 'tool-opus-clip',
    name: 'Opus Clip',
    category: 'Video AI',
    pricingType: 'Freemium',
    visits: '9.8M',
    visitsNum: 9800000,
    rating: 4.8,
    url: 'https://opus.pro',
    tagline: 'Repurpose 1 long video into 10 viral short clips with AI virality score predictions.',
    desc: 'Analyzes long YouTube videos and podcasts, extracts the most engaging hooks, and reformats into TikToks.',
    pros: ['Virality score helps pick best moments', 'Auto-reframes face to vertical 9:16', 'Dynamic emojis and captions'],
    cons: ['Credit quota on free tier'],
    features: ['AI Virality Score Engine', 'Auto Speaker Reframe', 'Animated Caption Presets'],
  },
  {
    id: 'tool-veed-io',
    name: 'Veed.io',
    category: 'Video AI',
    pricingType: 'Freemium',
    visits: '13.5M',
    visitsNum: 13500000,
    rating: 4.7,
    url: 'https://veed.io',
    tagline: 'Online video suite with AI auto-subtitles, background removal, avatars, and text-to-speech.',
    desc: 'Cloud video editor that runs in browser with automatic captions, audio cleanup, and video templates.',
    pros: ['Zero software download needed', 'Accurate auto-subtitle generation', 'Templates for all social sizes'],
    cons: ['Watermark on free tier exports'],
    features: ['In-Browser Cloud Editor', 'Auto Subtitles & Captioning', 'AI Green Screen Remover'],
  },
  {
    id: 'tool-viggle-ai',
    name: 'Viggle AI',
    category: 'Video AI',
    pricingType: 'Freemium',
    visits: '8.9M',
    visitsNum: 8900000,
    rating: 4.8,
    url: 'https://viggle.ai',
    tagline: 'Controllable character animation model that makes any character perform real dance and motion videos.',
    desc: 'Upload an image of a character or person and a motion video, and Viggle animates the character following the physics.',
    pros: ['Viral meme character animations', 'Physics-accurate motion transfer', 'Generous Discord & Web free tier'],
    cons: ['Best for single-character focused clips'],
    features: ['Character Motion Transfer', 'Discord Bot & Web Workspace', 'Background Green Screen Export'],
  },

  // ── 5. AUDIO AI (15 tools) ────────────────────────────────────────────────
  {
    id: 'tool-elevenlabs',
    name: 'ElevenLabs',
    category: 'Audio AI',
    pricingType: 'Freemium',
    visits: '28.5M',
    visitsNum: 28500000,
    rating: 4.9,
    url: 'https://elevenlabs.io',
    tagline: 'The leading AI voice generator, ultra-realistic voice cloning, and audio dubbing.',
    desc: 'Voice synthesis platform capable of human emotion, nuance, and voice cloning in 32+ languages.',
    pros: ['Unrivaled natural vocal inflections', 'Instant voice cloning from 1-minute audio', 'Multi-lingual automatic dubbing'],
    cons: ['Character count quotas on free tier'],
    features: ['Voice Cloning & Design', 'Emotional Speech Synthesis', 'AI Dubbing & Sound Effects'],
    deal: { discount: '80% OFF First Month', code: 'ELEVENFLUX', description: '80% off Starter tier.' },
    isFeatured: true,
  },
  {
    id: 'tool-suno',
    name: 'Suno AI',
    category: 'Audio AI',
    pricingType: 'Freemium',
    visits: '41.2M',
    visitsNum: 41200000,
    rating: 4.8,
    url: 'https://suno.com',
    tagline: 'Create full radio-quality songs with vocals and instrumentation in any genre from text.',
    desc: 'Generates complete 2-minute songs with vocals, lyrics, and production across rock, pop, hip-hop, and EDM.',
    pros: ['Full songs with verses and chorus', 'Radio quality sound mixing', 'Generous daily free credits'],
    cons: ['Commercial rights require Pro subscription'],
    features: ['Text-to-Full Song Generation', 'Custom Lyric Composer', 'Song Stem Separation'],
    deal: { discount: '25% OFF Pro Yearly', code: 'SUNOVIBES', description: '25% off Pro annual subscription.' },
    isFeatured: true,
  },
  {
    id: 'tool-udio',
    name: 'Udio',
    category: 'Audio AI',
    pricingType: 'Freemium',
    visits: '19.5M',
    visitsNum: 19500000,
    rating: 4.8,
    url: 'https://udio.com',
    tagline: 'AI music generator that produces expressive vocals and intricate musical arrangements.',
    desc: 'Built by former DeepMind researchers, Udio excels at vocal clarity, jazz, classical, and musical extensions.',
    pros: ['Vocal expression and runs', 'Intricate chord progressions', 'Track extending and inpainting'],
    cons: ['Generates in 32-second segments that require extension'],
    features: ['Expressive Vocal Nuance', 'Track Inpainting & Extension', 'Stem Separation Tools'],
  },
  {
    id: 'tool-speechify',
    name: 'Speechify',
    category: 'Audio AI',
    pricingType: 'Freemium',
    visits: '16.2M',
    visitsNum: 16200000,
    rating: 4.8,
    url: 'https://speechify.com',
    tagline: 'The #1 AI text-to-speech reader for books, PDFs, articles, and study materials.',
    desc: 'Reads any written text aloud at up to 4.5x speed with natural voices like Snoop Dogg and Gwyneth Paltrow.',
    pros: ['Speeds up reading retention dramatically', 'Celebrity voice narrators', 'Syncs across iOS, Mac, and Chrome'],
    cons: ['Premium voices require paid plan'],
    features: ['4.5x Natural Reading Speeds', 'OCR Photo to Speech', 'Cross-Platform Reading Sync'],
  },
  {
    id: 'tool-murf-ai',
    name: 'Murf.ai',
    category: 'Audio AI',
    pricingType: 'Freemium',
    visits: '6.8M',
    visitsNum: 6800000,
    rating: 4.7,
    url: 'https://murf.ai',
    tagline: 'AI voice generator for e-learning, product demos, presentations, and YouTube videos.',
    desc: 'Provides 120+ natural-sounding voices in 20+ languages with granular pitch, pause, and speed sliders.',
    pros: ['Fine-grained pitch and emphasis controls', 'Built-in video sync timeline', 'Enterprise team collaboration'],
    cons: ['Free version has download restrictions'],
    features: ['Pitch & Pause Granular Tuning', 'Video Sync Studio Timeline', '120+ Studio Voices'],
  },
  {
    id: 'tool-play-ht',
    name: 'Play.ht',
    category: 'Audio AI',
    pricingType: 'Freemium',
    visits: '5.9M',
    visitsNum: 5900000,
    rating: 4.7,
    url: 'https://play.ht',
    tagline: 'Ultra-realistic generative text-to-speech engine and real-time streaming voice API.',
    desc: 'Provides sub-200ms voice generation API for conversational AI bots, call centers, and audiobooks.',
    pros: ['Low-latency streaming API', 'Massive library of 800+ voices', 'Voice clone fidelity'],
    cons: ['API pricing can scale on large volumes'],
    features: ['Sub-200ms Streaming Voice API', '800+ Natural AI Voices', 'Custom Pronunciation Dictionary'],
  },
  {
    id: 'tool-whisper-openai',
    name: 'OpenAI Whisper',
    category: 'Audio AI',
    pricingType: 'Open Source',
    visits: '12.4M',
    visitsNum: 12400000,
    rating: 4.9,
    url: 'https://openai.com/research/whisper',
    tagline: 'Robust multi-lingual speech recognition and translation model with open weights.',
    desc: 'Trained on 680,000 hours of multi-lingual audio to provide near-human level transcription accuracy.',
    pros: ['100% free open-source weights', 'Handles heavy background noise and accents', 'Supports 99 languages'],
    cons: ['Requires command-line or API execution'],
    features: ['Open Source Speech Recognition', 'Direct Audio Translation to English', 'Accurate Punctuation & Timestamps'],
  },
  {
    id: 'tool-krisp',
    name: 'Krisp',
    category: 'Audio AI',
    pricingType: 'Freemium',
    visits: '7.8M',
    visitsNum: 7800000,
    rating: 4.8,
    url: 'https://krisp.ai',
    tagline: 'AI noise-cancellation app that removes background noise, barking dogs, and echoes from calls.',
    desc: 'Runs directly on your computer processor to eliminate background noise from microphone and incoming audio.',
    pros: ['Removes barking dogs, traffic, and baby cries instantly', 'Runs 100% locally on device', 'Low CPU usage'],
    cons: ['Free tier limited to 60 mins/day'],
    features: ['Two-Way Noise Cancellation', 'Virtual Background Echo Removal', 'AI Meeting Assistant Transcripts'],
  },
  {
    id: 'tool-soundraw',
    name: 'Soundraw',
    category: 'Audio AI',
    pricingType: 'Freemium',
    visits: '4.5M',
    visitsNum: 4500000,
    rating: 4.7,
    url: 'https://soundraw.io',
    tagline: 'AI music generator for content creators that creates royalty-free background music.',
    desc: 'Customize the mood, tempo, instruments, and track length with interactive waveform sliders.',
    pros: ['Royalty-free music license forever', 'Interactive song structure customization', 'Zero copyright strikes'],
    cons: ['Vocal synthesis not supported (instrumentals only)'],
    features: ['Royalty-Free Commercial License', 'Waveform Energy Editor', 'Custom Mood & Genre Selection'],
  },
  {
    id: 'tool-audiocraft-meta',
    name: 'AudioCraft / MusicGen',
    category: 'Audio AI',
    pricingType: 'Open Source',
    visits: '3.8M',
    visitsNum: 3800000,
    rating: 4.8,
    url: 'https://audiocraft.metademolab.com',
    tagline: 'Meta’s open-source generative audio research library for MusicGen and AudioGen.',
    desc: 'Generates complex music and environmental sound effects from simple text descriptions with open weights.',
    pros: ['Open weights and research code', 'Generate music matching melody inputs', 'Great for ambient sound design'],
    cons: ['Requires Python setup and GPU hardware'],
    features: ['Open-Source MusicGen Weights', 'Melody-Guided Generation', 'Environmental SoundFX Synthesis'],
  },
  {
    id: 'tool-lovo-ai',
    name: 'Lovo.ai (Genny)',
    category: 'Audio AI',
    pricingType: 'Freemium',
    visits: '5.2M',
    visitsNum: 5200000,
    rating: 4.7,
    url: 'https://lovo.ai',
    tagline: 'Award-winning AI voice generator and video editor with 500+ realistic voices.',
    desc: 'Combines text-to-speech with video editing, subtitles, and AI scriptwriting for marketing agencies.',
    pros: ['Over 500+ expressive voices', 'Built-in video timeline editor', 'Pronunciation editor'],
    cons: ['Rendering high-res video takes time'],
    features: ['500+ Studio Voices', 'Integrated Video Editor', 'Custom Voice Cloning'],
  },
  {
    id: 'tool-voicemod',
    name: 'Voicemod',
    category: 'Audio AI',
    pricingType: 'Freemium',
    visits: '8.4M',
    visitsNum: 8400000,
    rating: 4.7,
    url: 'https://voicemod.net',
    tagline: 'Real-time AI voice changer and soundboard for Discord, Twitch, and gaming.',
    desc: 'Modifies your voice in real time with sub-millisecond latency for streamers and gamers.',
    pros: ['Zero latency real-time voice shifting', 'Massive soundboard integration', 'Discord & OBS compatible'],
    cons: ['Full voice catalog requires Pro purchase'],
    features: ['Real-Time AI Voice Pitch Shifting', 'Custom Soundboard Hotkeys', 'Discord & OBS Direct Plugin'],
  },
  {
    id: 'tool-podcastle',
    name: 'Podcastle',
    category: 'Audio AI',
    pricingType: 'Freemium',
    visits: '4.9M',
    visitsNum: 4900000,
    rating: 4.7,
    url: 'https://podcastle.ai',
    tagline: 'Studio-quality recording and editing software for podcasters and content creators.',
    desc: 'Local uncompressed audio recording with Magic Dust AI filter that removes background noise.',
    pros: ['Separate uncompressed audio tracks per remote guest', 'One-click Magic Dust enhancement', 'Text-based audio editor'],
    cons: ['Video resolution options capped on free tier'],
    features: ['Multi-Track Remote Recording', 'Magic Dust Audio Restorer', 'Text-Based Audio Trimming'],
  },
  {
    id: 'tool-resemble-ai',
    name: 'Resemble AI',
    category: 'Audio AI',
    pricingType: 'Paid',
    visits: '3.1M',
    visitsNum: 3100000,
    rating: 4.8,
    url: 'https://resemble.ai',
    tagline: 'Enterprise voice cloning platform with real-time deepfake detection and watermarking.',
    desc: 'Creates synthetic voices with granular emotional inflections, and detects AI audio deepfakes with Resemble Detect.',
    pros: ['Deepfake audio detection capabilities', 'Granular phoneme pronunciation editing', 'Enterprise watermarking'],
    cons: ['Geared towards enterprise budgets'],
    features: ['Resemble Detect Deepfake Shield', 'Per-Phoneme Emotional Sliders', 'Cryptographic Audio Watermark'],
  },
  {
    id: 'tool-moises-ai',
    name: 'Moises.ai',
    category: 'Audio AI',
    pricingType: 'Freemium',
    visits: '9.6M',
    visitsNum: 9600000,
    rating: 4.8,
    url: 'https://moises.ai',
    tagline: 'The musician’s app: isolate vocals, drums, bass, and chords with AI stem separation.',
    desc: 'Separate vocals, drums, bass, and keys from any song, detect BPM, and transpose pitches in seconds.',
    pros: ['Clean vocal and instrument stem separation', 'Smart metronome and chord detection', 'Great practice tool for musicians'],
    cons: ['Free tier limited to 5 songs per month'],
    features: ['AI Stem Separation', 'Smart Metronome & Pitch Changer', 'Chord Detection in Real Time'],
  },

  // ── 6. COPYWRITING (15 tools) ─────────────────────────────────────────────
  {
    id: 'tool-jasper',
    name: 'Jasper AI',
    category: 'Copywriting',
    pricingType: 'Paid',
    visits: '8.9M',
    visitsNum: 8900000,
    rating: 4.8,
    url: 'https://jasper.ai',
    tagline: 'Enterprise generative AI platform for high-converting marketing copy and brand voice.',
    desc: 'Writes on-brand blog posts, ad campaigns, and social media copy across 30+ languages with style guide enforcement.',
    pros: ['Strict brand voice customization', 'End-to-end multi-channel campaigns', 'Built-in Surfer SEO integration'],
    cons: ['No permanent free tier'],
    features: ['Company Brand Voice Memory', 'Multi-Channel Campaign Generator', 'SEO Mode via Surfer SEO'],
    deal: { discount: '20% OFF ANNUAL', code: 'JASPER20', description: '20% off Creator and Pro annual plans.' },
    isFeatured: true,
  },
  {
    id: 'tool-copy-ai',
    name: 'Copy.ai',
    category: 'Copywriting',
    pricingType: 'Freemium',
    visits: '11.4M',
    visitsNum: 11400000,
    rating: 4.8,
    url: 'https://copy.ai',
    tagline: 'GTM AI platform that automates sales outreach, marketing copy, and localization.',
    desc: 'Automates go-to-market workflows, prospect research, cold emails, and multi-channel marketing campaigns.',
    pros: ['Workflow automations for outbound sales', 'Infobase brand voice memory', 'Generous free tier'],
    cons: ['Team seats require Pro upgrade'],
    features: ['Automated GTM Workflows', 'Brand Infobase Memory', 'Multi-Language Copywriting'],
    deal: { discount: '20% OFF PRO', code: 'COPYAI20', description: '20% off annual plan.' },
  },
  {
    id: 'tool-writesonic',
    name: 'Writesonic',
    category: 'Copywriting',
    pricingType: 'Freemium',
    visits: '9.2M',
    visitsNum: 9200000,
    rating: 4.7,
    url: 'https://writesonic.com',
    tagline: 'AI content generator and SEO optimizer for rankable blog posts, ads, and landing pages.',
    desc: 'Generates 3,000-word factual SEO articles with real-time web search grounding and Chatsonic assistant.',
    pros: ['Factual real-time search grounding', 'One-click long-form article writer', 'Built-in SEO score auditing'],
    cons: ['Word counts consume credits'],
    features: ['Article Writer 6.0 Engine', 'Chatsonic Conversational Assistant', 'Internal Linking Auto-Suggest'],
  },
  {
    id: 'tool-rytr',
    name: 'Rytr',
    category: 'Copywriting',
    pricingType: 'Freemium',
    visits: '5.6M',
    visitsNum: 5600000,
    rating: 4.7,
    url: 'https://rytr.me',
    tagline: 'Affordable, easy-to-use AI writing assistant for emails, blogs, social posts, and ad copy.',
    desc: 'Generates catchphrases, product descriptions, email pitches, and blog intros with 40+ use cases and 20+ tones.',
    pros: ['Budget-friendly pricing', '40+ quick-use copywriting templates', 'Built-in plagiarism checker'],
    cons: ['Long-form reasoning simpler than Jasper'],
    features: ['40+ Use Case Templates', '20+ Tone of Voice Pickers', 'Built-In Plagiarism Audit'],
  },
  {
    id: 'tool-surfer-seo',
    name: 'Surfer SEO',
    category: 'Copywriting',
    pricingType: 'Paid',
    visits: '6.4M',
    visitsNum: 6400000,
    rating: 4.9,
    url: 'https://surferseo.com',
    tagline: 'Content intelligence platform that analyzes SERP competitors to help your articles rank #1 on Google.',
    desc: 'Analyzes top 10 ranking pages for any keyword to give guidelines on word count, keyword density, and NLP terms.',
    pros: ['Proven rankings track record', 'Real-time Content Score meter', 'Audit existing pages to reclaim traffic'],
    cons: ['Requires active paid plan'],
    features: ['SERP Competitor Keyword Analysis', 'Real-Time Content Score Meter', 'Internal Linking Opportunities'],
  },
  {
    id: 'tool-quillbot',
    name: 'QuillBot',
    category: 'Copywriting',
    pricingType: 'Freemium',
    visits: '72.0M',
    visitsNum: 72000000,
    rating: 4.8,
    url: 'https://quillbot.com',
    tagline: 'The world’s most popular AI paraphrasing tool, grammar checker, and summarizer.',
    desc: 'Rewrites sentences in multiple modes (Formal, Creative, Simple, Fluent) while preserving original intent.',
    pros: ['Exceptional natural paraphrasing', 'Color-coded synonym replacement slider', 'Integrated citation generator'],
    cons: ['Free tier has character limits per rewrite'],
    features: ['Multi-Mode Paraphraser', 'Integrated Grammar & Tone Checker', 'Citation Generator for Research'],
  },
  {
    id: 'tool-grammarly-ai',
    name: 'Grammarly AI',
    category: 'Copywriting',
    pricingType: 'Freemium',
    visits: '110M',
    visitsNum: 110000000,
    rating: 4.9,
    url: 'https://grammarly.com',
    tagline: 'AI communication assistant for mistake-free writing across all desktop apps and browsers.',
    desc: 'Corrects grammar, enhances clarity, suggests vocabulary, and drafts replies across Slack, Gmail, and Word.',
    pros: ['Works seamlessly inside every text box on your computer', 'Tone detector helps maintain professionalism', 'Enterprise privacy standards'],
    cons: ['Full generative AI prompts require Premium tier'],
    features: ['Universal Desktop & Browser Check', 'Tone & Clarity Rephraser', 'Automated One-Click Email Replies'],
  },
  {
    id: 'tool-wordtune',
    name: 'Wordtune',
    category: 'Copywriting',
    pricingType: 'Freemium',
    visits: '8.1M',
    visitsNum: 8100000,
    rating: 4.7,
    url: 'https://wordtune.com',
    tagline: 'AI writing companion that helps you say exactly what you mean with smart rephrasing.',
    desc: 'Offers alternate phrasings for sentences, shortens or expands text, and adjusts tone from casual to formal.',
    pros: ['Provides 10+ smart alternatives per sentence', 'Casual vs Formal instant toggle', 'Superb Chrome extension integration'],
    cons: ['Free plan gives 10 rewrites per day'],
    features: ['Sentence Rewrite Alternatives', 'Casual & Formal Tone Shifter', 'Text Length Expander & Shortener'],
  },
  {
    id: 'tool-sudowrite',
    name: 'Sudowrite',
    category: 'Copywriting',
    pricingType: 'Paid',
    visits: '3.4M',
    visitsNum: 3400000,
    rating: 4.9,
    url: 'https://sudowrite.com',
    tagline: 'The AI writing tool designed specifically for fiction writers, novelists, and storytellers.',
    desc: 'Helps fiction authors overcome writer’s block with sensory descriptions, plot brainstorming, and Story Bible.',
    pros: ['Understands character arcs and pacing', 'Sensory description engine (smell, touch, sound)', 'Story Bible keeps world lore consistent'],
    cons: ['Optimized for creative fiction, not marketing copy'],
    features: ['Story Bible Character & World Memory', 'Sensory Detail Generator', 'Canvas Brainstorm Plot Outliner'],
  },
  {
    id: 'tool-hypotenuse-ai',
    name: 'Hypotenuse AI',
    category: 'Copywriting',
    pricingType: 'Paid',
    visits: '2.8M',
    visitsNum: 2800000,
    rating: 4.7,
    url: 'https://hypotenuse.ai',
    tagline: 'AI content generator tailored for e-commerce product descriptions, blog posts, and category pages.',
    desc: 'Connects directly to Shopify and Amazon to generate hundreds of SEO-optimized product descriptions in bulk.',
    pros: ['Bulk product description generator', 'Direct Shopify CSV and API sync', 'Factual content research engine'],
    cons: ['Specialized for retail rather than general essays'],
    features: ['Bulk E-Commerce Description Writer', 'Shopify & Amazon Integration', 'Factual Blog Article Builder'],
  },
  {
    id: 'tool-anyword',
    name: 'Anyword',
    category: 'Copywriting',
    pricingType: 'Paid',
    visits: '2.5M',
    visitsNum: 2500000,
    rating: 4.8,
    url: 'https://anyword.com',
    tagline: 'Performance copywriting platform with predictive performance scoring for marketers.',
    desc: 'Scores ad copy and email subject lines with a predictive conversion score before launching campaigns.',
    pros: ['Predicts copy performance before spending ad budget', 'Analyzes past ad data to learn top angles', 'Integrates with Meta & Google Ads'],
    cons: ['Priced for professional marketing teams'],
    features: ['Predictive Performance Score (PPS)', 'Custom Brand Voice & Guidelines', 'Meta & Google Ads Campaign Sync'],
  },
  {
    id: 'tool-frase-io',
    name: 'Frase.io',
    category: 'Copywriting',
    pricingType: 'Paid',
    visits: '3.6M',
    visitsNum: 3600000,
    rating: 4.7,
    url: 'https://frase.io',
    tagline: 'SEO content optimization tool that creates research briefs and outlines in minutes.',
    desc: 'Scrapes Google search results to curate research briefs, headings, and FAQ questions for any target query.',
    pros: ['Automates competitor research briefs', 'Intuitive content scoring editor', 'Generates outlines in under 2 minutes'],
    cons: ['User interface has a learning curve'],
    features: ['Automated SERP Research Briefs', 'Heading & Outline Generator', 'Real-Time Content Optimization Score'],
  },
  {
    id: 'tool-semrush-contentshake',
    name: 'ContentShake AI by Semrush',
    category: 'Copywriting',
    pricingType: 'Paid',
    visits: '4.2M',
    visitsNum: 4200000,
    rating: 4.8,
    url: 'https://semrush.com/contentshake',
    tagline: 'Semrush’s smart content writer that combines competitor search data with generative AI.',
    desc: 'Recommends trending content topics and writes full SEO articles with Semrush keyword data.',
    pros: ['Backed by Semrush search volume and keyword metrics', 'One-click publish to WordPress', 'Suggests trending topics in your niche'],
    cons: ['Requires Semrush subscription or ContentShake add-on'],
    features: ['Semrush SEO Data Integration', 'One-Click WordPress Publishing', 'Trending Topic Recommender'],
  },
  {
    id: 'tool-scalenut',
    name: 'Scalenut',
    category: 'Copywriting',
    pricingType: 'Paid',
    visits: '2.9M',
    visitsNum: 2900000,
    rating: 4.7,
    url: 'https://scalenut.com',
    tagline: 'All-in-one SEO content lifecycle platform from keyword research to article writing and auditing.',
    desc: 'Cruise Mode writes 2,000+ word articles in 5 minutes with real-time NLP key terms and competitor metrics.',
    pros: ['Cruise Mode writes long articles fast', 'Topic cluster planning engine', 'Includes keyword planner'],
    cons: ['Requires human editing for voice and tone'],
    features: ['Cruise Mode 5-Minute Article Writer', 'Topic Cluster & Keyword Planner', 'NLP Term Optimizer'],
  },
  {
    id: 'tool-peppertype',
    name: 'Peppertype.ai',
    category: 'Copywriting',
    pricingType: 'Paid',
    visits: '2.1M',
    visitsNum: 2100000,
    rating: 4.6,
    url: 'https://peppercontent.io',
    tagline: 'Enterprise content marketing platform combining AI copy generation with human editorial workflows.',
    desc: 'Enterprise platform that streamlines multi-channel content operations, SEO ideation, and team approvals.',
    pros: ['Enterprise review and editorial governance', 'Custom enterprise brand dictionaries', 'Audit trail for revisions'],
    cons: ['Tailored to enterprise accounts'],
    features: ['Editorial Approval Governance', 'Multi-Channel Content Suite', 'Brand Guideline Compliance'],
  },

  // ── 7. DATA & ANALYTICS (15 tools) ────────────────────────────────────────
  {
    id: 'tool-julius',
    name: 'Julius AI',
    category: 'Data & Analytics',
    pricingType: 'Freemium',
    visits: '6.2M',
    visitsNum: 6200000,
    rating: 4.8,
    url: 'https://julius.ai',
    tagline: 'The AI Data Analyst that cleans spreadsheets, runs models, and visualizes trends.',
    desc: 'Connects to CSVs, Excel, and SQL databases. Ask questions in plain English to execute Python calculations.',
    pros: ['Interprets complex multi-tab Excel files', 'Outputs clean Python/R code', 'Zero statistical knowledge needed'],
    cons: ['Free plan limited to 15 queries per month'],
    features: ['Excel, CSV & SQL Database Connector', 'Automated Outlier Detection', 'Publication-Ready Charts'],
    deal: { discount: '15% OFF PRO', code: 'JULIUSAI', description: '15% off first 3 months of Julius Pro.' },
    isFeatured: true,
  },
  {
    id: 'tool-chatgpt-data-analysis',
    name: 'ChatGPT Data Analysis',
    category: 'Data & Analytics',
    pricingType: 'Freemium',
    visits: '90M',
    visitsNum: 90000000,
    rating: 4.9,
    url: 'https://chatgpt.com',
    tagline: 'OpenAI’s sandboxed Python execution engine for analyzing datasets, math, and graphs.',
    desc: 'Upload multi-gigabyte CSVs, JSON, or Excel sheets to run Python code, statistical tests, and interactive plots.',
    pros: ['Real Python code execution in sandboxed VM', 'Exports clean matplotlib and seaborn charts', 'Fast data transformations'],
    cons: ['Session state resets when conversation expires'],
    features: ['Sandboxed Python Execution', 'Statistical Regression & Modeling', 'File Cleanup & Data Wrangling'],
  },
  {
    id: 'tool-rows-com',
    name: 'Rows.com',
    category: 'Data & Analytics',
    pricingType: 'Freemium',
    visits: '3.8M',
    visitsNum: 3800000,
    rating: 4.8,
    url: 'https://rows.com',
    tagline: 'The modern spreadsheet with built-in AI analyst, web enrichment, and database integrations.',
    desc: 'Combines Google Sheets simplicity with AI data extraction, LinkedIn company enrichment, and dashboard publishing.',
    pros: ['Native AI analyst formula', 'Built-in integrations with Stripe, Google Analytics, and SQL', 'Modern shareable dashboards'],
    cons: ['Very large datasets (1M+ rows) best suited for SQL'],
    features: ['AI Analyst Spreadsheet Formulas', 'Live API Integrations (Stripe, GA4)', 'Interactive Dashboard Publishing'],
  },
  {
    id: 'tool-hex-tech',
    name: 'Hex',
    category: 'Data & Analytics',
    pricingType: 'Freemium',
    visits: '2.9M',
    visitsNum: 2900000,
    rating: 4.8,
    url: 'https://hex.tech',
    tagline: 'Collaborative analytics platform combining SQL, Python, and Magic AI for modern data teams.',
    desc: 'Magic AI writes SQL queries, fixes Python errors, and builds interactive data apps connected to Snowflake and BigQuery.',
    pros: ['Seamless blend of SQL and Python notebooks', 'Magic AI understands warehouse schema', 'One-click interactive app sharing'],
    cons: ['Designed for data teams with SQL knowledge'],
    features: ['Magic AI SQL & Python Co-Pilot', 'Snowflake & BigQuery Warehouse Sync', 'Interactive Data App Builder'],
  },
  {
    id: 'tool-tableau-pulse',
    name: 'Tableau Pulse',
    category: 'Data & Analytics',
    pricingType: 'Paid',
    visits: '18.4M',
    visitsNum: 18400000,
    rating: 4.7,
    url: 'https://tableau.com',
    tagline: 'Next-generation BI experience that delivers personalized metric digests and automated drivers.',
    desc: 'Transforms raw dashboards into plain-language automated digests that explain why metrics changed.',
    pros: ['Explains the root cause behind metric spikes', 'Personalized digests delivered to Slack/Teams', 'Enterprise governance and security'],
    cons: ['Requires Tableau Cloud enterprise deployment'],
    features: ['Automated Metric Driver Explanations', 'Personalized KPI Digest Delivery', 'Natural Language Q&A on Metrics'],
  },
  {
    id: 'tool-power-bi-copilot',
    name: 'Power BI Copilot',
    category: 'Data & Analytics',
    pricingType: 'Paid',
    visits: '24.0M',
    visitsNum: 24000000,
    rating: 4.7,
    url: 'https://powerbi.microsoft.com',
    tagline: 'Microsoft’s generative AI copilot for Power BI reports, DAX formulas, and data narrative.',
    desc: 'Generates report pages, writes complex DAX formulas, and summarizes visual insights into executive briefs.',
    pros: ['Generates full Power BI report pages in seconds', 'Assists with difficult DAX formula calculations', 'Direct Microsoft Fabric integration'],
    cons: ['Requires Microsoft Fabric or Power BI Premium capacity'],
    features: ['Automated Report Page Synthesis', 'DAX Formula Assistant', 'Executive Summary Visual Cards'],
  },
  {
    id: 'tool-polymer-search',
    name: 'Polymer Search',
    category: 'Data & Analytics',
    pricingType: 'Paid',
    visits: '1.8M',
    visitsNum: 1800000,
    rating: 4.7,
    url: 'https://polymersearch.com',
    tagline: 'Turns spreadsheets into interactive, searchable, and AI-powered databases without code.',
    desc: 'Upload a CSV and Polymer analyzes data types to auto-build pivot tables, graphs, and filters.',
    pros: ['Zero technical knowledge needed', 'Auto-generates clean visual dashboards', 'Fast client-side filtering'],
    cons: ['Not designed for multi-table relational joins'],
    features: ['Instant Auto-Generated BI Dashboards', 'Faceted Search & Filter Engine', 'Embeddable Interactive Visuals'],
  },
  {
    id: 'tool-columns-ai',
    name: 'Columns AI',
    category: 'Data & Analytics',
    pricingType: 'Freemium',
    visits: '1.4M',
    visitsNum: 1400000,
    rating: 4.8,
    url: 'https://columns.ai',
    tagline: 'AI visual storyteller that creates stunning data presentations and visual graphs from raw numbers.',
    desc: 'Transforms spreadsheets into magazine-quality charts and data stories with automated narrative annotations.',
    pros: ['Magazine-grade chart aesthetics', 'Automated written takeaway callouts on charts', 'Connects to Notion and Google Drive'],
    cons: ['Advanced data prep best handled prior to import'],
    features: ['Magazine-Quality Chart Styling', 'Automated Narrative Callouts', 'Notion & Slack Visual Embeds'],
  },
  {
    id: 'tool-akkio',
    name: 'Akkio',
    category: 'Data & Analytics',
    pricingType: 'Paid',
    visits: '1.9M',
    visitsNum: 1900000,
    rating: 4.7,
    url: 'https://akkio.com',
    tagline: 'No-code predictive AI and analytics platform for agencies and growth marketing teams.',
    desc: 'Build predictive machine learning models to forecast lead conversion, churn, and revenue without writing code.',
    pros: ['Trains predictive models in under 10 minutes', 'No data science degree needed', 'Chat with your data interface'],
    cons: ['Requires clean historical training dataset'],
    features: ['No-Code Machine Learning Training', 'Lead Scoring & Churn Forecasting', 'Chat Explore Data Assistant'],
  },
  {
    id: 'tool-formula-bot',
    name: 'Formula Bot',
    category: 'Data & Analytics',
    pricingType: 'Freemium',
    visits: '3.2M',
    visitsNum: 3200000,
    rating: 4.8,
    url: 'https://formulabot.com',
    tagline: 'AI assistant for Excel and Google Sheets formulas, script generation, and data analysis.',
    desc: 'Converts English instructions into complex Excel/Google Sheets formulas and Google Apps Scripts.',
    pros: ['Solves nested VLOOKUP, INDEX/MATCH, and regex', 'Generates Google Apps Script and VBA macros', 'Add-in integrates directly into Excel'],
    cons: ['Free version has monthly formula quota'],
    features: ['English to Excel/Sheets Formulas', 'VBA & Google Apps Script Generator', 'Native Excel Add-In Integration'],
  },
  {
    id: 'tool-monkeylearn',
    name: 'MonkeyLearn',
    category: 'Data & Analytics',
    pricingType: 'Paid',
    visits: '1.6M',
    visitsNum: 1600000,
    rating: 4.7,
    url: 'https://monkeylearn.com',
    tagline: 'No-code text analytics and sentiment analysis platform for customer feedback and survey data.',
    desc: 'Classifies customer support tickets, NPS survey reviews, and feedback with custom AI classification models.',
    pros: ['Accurate sentiment and topic classification', 'Integrates with Zendesk and Freshdesk', 'Clean visual dashboard Studio'],
    cons: ['Specialized in text analysis rather than numerical regression'],
    features: ['Custom Sentiment Classification', 'NPS & Survey Analysis Studio', 'Zendesk & CRM Connectors'],
  },
  {
    id: 'tool-deepnote-ai',
    name: 'Deepnote AI',
    category: 'Data & Analytics',
    pricingType: 'Freemium',
    visits: '2.4M',
    visitsNum: 2400000,
    rating: 4.8,
    url: 'https://deepnote.com',
    tagline: 'Collaborative data science notebook with AI code generation, auto-complete, and SQL blocks.',
    desc: 'Cloud Jupyter notebook where data teams collaborate in real-time with AI that writes pandas code and fixes errors.',
    pros: ['Real-time multi-user multiplayer notebooks', 'AI writes pandas and fixes syntax errors', 'Connects to any data warehouse or S3'],
    cons: ['Requires familiarity with Python notebooks'],
    features: ['Multiplayer Jupyter Cloud Environment', 'Context-Aware Pandas Co-Pilot', 'Interactive SQL & Python Cells'],
  },
  {
    id: 'tool-databricks-mosaic',
    name: 'Databricks Mosaic AI',
    category: 'Data & Analytics',
    pricingType: 'Paid',
    visits: '14.2M',
    visitsNum: 14200000,
    rating: 4.9,
    url: 'https://databricks.com',
    tagline: 'Unified data intelligence platform for training custom models, RAG pipelines, and enterprise analytics.',
    desc: 'Combines data lakehouse architecture with generative AI to build custom models and query enterprise data.',
    pros: ['Handles petabyte-scale lakehouse data', 'End-to-end RAG and fine-tuning suite', 'Enterprise security and governance'],
    cons: ['Enterprise procurement and infrastructure costs'],
    features: ['Lakehouse Data Intelligence Engine', 'Custom LLM Training & Fine-Tuning', 'Enterprise Unity Catalog Governance'],
  },
  {
    id: 'tool-thoughtspot-sage',
    name: 'ThoughtSpot Sage',
    category: 'Data & Analytics',
    pricingType: 'Paid',
    visits: '2.1M',
    visitsNum: 2100000,
    rating: 4.7,
    url: 'https://thoughtspot.com',
    tagline: 'Search and AI-driven analytics that lets anyone ask questions of cloud data in natural language.',
    desc: 'Combines search with generative AI to let business users ask questions of Snowflake or Databricks.',
    pros: ['True natural language search on live warehouses', 'Auto-generated chart visualizations', 'Scales across non-technical users'],
    cons: ['Requires enterprise cloud warehouse integration'],
    features: ['Natural Language Data Warehouse Querying', 'Instant Auto-Visualization Engine', 'Interactive Liveboards'],
  },
  {
    id: 'tool-coefficient-io',
    name: 'Coefficient',
    category: 'Data & Analytics',
    pricingType: 'Freemium',
    visits: '2.7M',
    visitsNum: 2700000,
    rating: 4.8,
    url: 'https://coefficient.io',
    tagline: 'Connect live business systems like Salesforce, HubSpot, and Snowflake directly to Google Sheets and Excel.',
    desc: 'Syncs live live CRM, database, and marketing data into Google Sheets and Excel with AI formula assistance.',
    pros: ['Two-way live data sync with business tools', 'AI spreadsheet builder inside Sheets', 'Automated scheduled snapshot refreshes'],
    cons: ['Data volume governed by spreadsheet cell limits'],
    features: ['Live 2-Way CRM & Warehouse Sync', 'AI Spreadsheet Formula Builder', 'Automated Scheduled Data Refreshes'],
  },

  // ── 8. AGENTS (15 tools) ──────────────────────────────────────────────────
  {
    id: 'tool-devin',
    name: 'Devin AI',
    category: 'Agents',
    pricingType: 'Paid',
    visits: '11.5M',
    visitsNum: 11500000,
    rating: 4.8,
    url: 'https://cognition.ai',
    tagline: 'The world’s first autonomous AI software engineer that executes real coding tasks.',
    desc: 'Equipped with sandboxed shell, code editor, and browser to plan, build, debug, and submit PRs autonomously.',
    pros: ['Fully sandboxed development environment', 'Resolves GitHub issues end-to-end', 'Self-corrects compilation errors'],
    cons: ['Waitlist and enterprise pricing'],
    features: ['Autonomous Sandboxed Shell & Browser', 'End-to-End Pull Request Synthesis', 'SWE-Bench SOTA Benchmark Record'],
    deal: { discount: 'PRIORITY PASS', code: 'DEVINFLUX', description: 'Skip standard waitlist.' },
    isFeatured: true,
  },
  {
    id: 'tool-autogpt',
    name: 'AutoGPT',
    category: 'Agents',
    pricingType: 'Open Source',
    visits: '8.4M',
    visitsNum: 8400000,
    rating: 4.7,
    url: 'https://autogpt.net',
    tagline: 'The pioneering open-source autonomous agent framework for continuous task execution.',
    desc: 'Chains LLM thoughts together to achieve goals autonomously with internet browsing and file management.',
    pros: ['Huge open-source community', 'Modular block builder GUI available', 'Completely free to self-host'],
    cons: ['Can enter infinite loops without explicit constraints'],
    features: ['Continuous Goal-Oriented Reasoning Loop', 'Visual Block Agent Builder', 'Multi-Agent Communication Protocol'],
    deal: { discount: '100% Free Open Source', code: 'AUTOGPTOPEN', description: 'Open source on GitHub.' },
  },
  {
    id: 'tool-crewai',
    name: 'CrewAI',
    category: 'Agents',
    pricingType: 'Open Source',
    visits: '7.8M',
    visitsNum: 7800000,
    rating: 4.9,
    url: 'https://crewai.com',
    tagline: 'Cutting-edge framework for orchestrating role-playing autonomous AI agent teams.',
    desc: 'Empowers developers to assign specific roles, tools, and goals to AI agents that collaborate on complex tasks.',
    pros: ['Role-based collaborative agent architecture', 'Works with any LLM (local or cloud)', 'Intuitive Python API'],
    cons: ['Requires Python engineering to build custom crews'],
    features: ['Role-Playing Agent Swarms', 'Sequential & Hierarchical Delegation', 'Tool-Calling & Memory Store'],
  },
  {
    id: 'tool-ms-copilot-studio',
    name: 'Microsoft Copilot Studio',
    category: 'Agents',
    pricingType: 'Paid',
    visits: '14.5M',
    visitsNum: 14500000,
    rating: 4.7,
    url: 'https://copilotstudio.microsoft.com',
    tagline: 'Low-code tool to customize Copilot and build autonomous agents for enterprise workflows.',
    desc: 'Build customized autonomous agents that trigger on business events, automate ERP/CRM workflows, and triage customer inquiries.',
    pros: ['Deep Microsoft 365 and Power Automate sync', 'Enterprise role-based security & governance', 'Low-code visual canvas'],
    cons: ['Requires Microsoft enterprise tenant setup'],
    features: ['Low-Code Agent Canvas Builder', 'Event-Driven Autonomous Triggers', 'Power Automate 1,000+ Connectors'],
  },
  {
    id: 'tool-openhands',
    name: 'OpenHands (formerly OpenDevin)',
    category: 'Agents',
    pricingType: 'Open Source',
    visits: '5.2M',
    visitsNum: 5200000,
    rating: 4.8,
    url: 'https://all-hands.dev',
    tagline: 'Open-source autonomous AI software developer equipped with command line and browser.',
    desc: 'Community-driven software engineer that modifies repositories, runs unit tests in Docker, and browsing docs.',
    pros: ['100% open-source alternative to Devin', 'Runs inside isolated Docker container', 'Community-driven development'],
    cons: ['Requires Docker environment to run safely'],
    features: ['Docker Sandboxed Execution', 'Interactive Web UI & Terminal', 'GitHub PR Automation'],
  },
  {
    id: 'tool-langgraph',
    name: 'LangGraph by LangChain',
    category: 'Agents',
    pricingType: 'Open Source',
    visits: '12.8M',
    visitsNum: 12800000,
    rating: 4.9,
    url: 'https://langchain.com',
    tagline: 'Framework for building resilient, controllable multi-agent applications with cycles and state.',
    desc: 'Graph-based coordination engine that gives developers complete control over multi-agent workflows and human-in-the-loop loops.',
    pros: ['Supports cyclical reasoning loops with state', 'Human-in-the-loop inspection and pause', 'Industry standard in production AI'],
    cons: ['Requires software development knowledge'],
    features: ['Cyclical Multi-Agent Graphs', 'Human-in-the-Loop State Pause', 'Streaming State Time-Travel Debugging'],
  },
  {
    id: 'tool-manus-ai',
    name: 'Manus AI',
    category: 'Agents',
    pricingType: 'Paid',
    visits: '9.4M',
    visitsNum: 9400000,
    rating: 4.8,
    url: 'https://manus.im',
    tagline: 'General-purpose autonomous agent that navigates complex computer tasks from end-to-end.',
    desc: 'Multi-modal autonomous agent that navigates the web, extracts structured data, and completes administrative processes.',
    pros: ['Autonomous browser interaction', 'Delivers complex research packets', 'High task completion reliability'],
    cons: ['Waitlist and invitation model'],
    features: ['Full Computer & Browser Automation', 'End-to-End Multi-Step Task Resolution', 'Structured Artifact Delivery'],
  },
  {
    id: 'tool-agentforce-salesforce',
    name: 'Agentforce by Salesforce',
    category: 'Agents',
    pricingType: 'Paid',
    visits: '21.0M',
    visitsNum: 21000000,
    rating: 4.7,
    url: 'https://salesforce.com/agentforce',
    tagline: 'Autonomous AI agents that augment your workforce across service, sales, and marketing.',
    desc: 'Deploys autonomous agents that analyze customer inquiries, take actions across CRM records, and resolve tickets.',
    pros: ['Direct integration with Salesforce Data Cloud', 'Zero hallucinations through Atlas reasoning engine', '24/7 automated tier-1 resolution'],
    cons: ['High enterprise licensing tier'],
    features: ['Atlas Reasoning Engine', 'Salesforce Data Cloud Grounding', 'Autonomous Omnichannel Support'],
  },
  {
    id: 'tool-camel-ai',
    name: 'Camel AI',
    category: 'Agents',
    pricingType: 'Open Source',
    visits: '2.6M',
    visitsNum: 2600000,
    rating: 4.8,
    url: 'https://camel-ai.org',
    tagline: 'First communicative agent framework for autonomous multi-agent cooperation and simulation.',
    desc: 'Pioneered communicative agent cooperative role-play where agents talk to each other to complete complex projects.',
    pros: ['First academic communicative agent library', 'Multi-agent society simulations', 'Rich role-playing prompts'],
    cons: ['Primarily academic and developer focused'],
    features: ['Inception Prompting Architecture', 'Role-Playing Multi-Agent Societies', 'Autonomous Problem Solving Loops'],
  },
  {
    id: 'tool-babyagi',
    name: 'BabyAGI',
    category: 'Agents',
    pricingType: 'Open Source',
    visits: '2.4M',
    visitsNum: 2400000,
    rating: 4.7,
    url: 'https://babyagi.org',
    tagline: 'Classic AI-powered task execution system that prioritizes and executes task queues.',
    desc: 'Autonomous agent that creates, prioritizes, and executes tasks based on previous completions.',
    pros: ['Minimalist, easy-to-understand codebase', 'Infinite task loop prioritization', 'Free open source'],
    cons: ['Basic compared to modern graph frameworks like LangGraph'],
    features: ['Task Execution & Creation Loop', 'Vector Memory Storage', 'Autonomous Priority Re-Sorting'],
  },
  {
    id: 'tool-multion-ai',
    name: 'MultiOn',
    category: 'Agents',
    pricingType: 'Freemium',
    visits: '3.6M',
    visitsNum: 3600000,
    rating: 4.8,
    url: 'https://multion.ai',
    tagline: 'Personal AI web agent that navigates the web to book flights, fill forms, and order food.',
    desc: 'Autonomous browser agent API that logs into websites, clicks buttons, solves CAPTCHAs, and executes transactions.',
    pros: ['True autonomous web browser actions', 'Handles dynamic JavaScript web pages', 'API ready for developers'],
    cons: ['Web navigation speed depends on target site latency'],
    features: ['Autonomous Browser Navigation API', 'Form Filling & Transaction Execution', 'Multi-Step Web Crawling'],
  },
  {
    id: 'tool-gumloop',
    name: 'Gumloop',
    category: 'Agents',
    pricingType: 'Freemium',
    visits: '3.2M',
    visitsNum: 3200000,
    rating: 4.8,
    url: 'https://gumloop.com',
    tagline: 'Visual AI workflow builder that automates web scraping, data extraction, and operations.',
    desc: 'No-code drag-and-drop canvas to build autonomous AI agents that scrape sites, enrich spreadsheets, and draft emails.',
    pros: ['Visual node-based canvas interface', 'Built-in web scraping and OCR nodes', 'Fast execution pipeline'],
    cons: ['Credit quota on free tier'],
    features: ['Visual Drag-and-Drop Workflow Canvas', 'Headless Browser Scraping Nodes', 'Automated Spreadsheet Enrichment'],
  },
  {
    id: 'tool-relevance-ai',
    name: 'Relevance AI',
    category: 'Agents',
    pricingType: 'Freemium',
    visits: '4.8M',
    visitsNum: 4800000,
    rating: 4.8,
    url: 'https://relevanceai.com',
    tagline: 'Build and hire an autonomous AI workforce for sales, operations, and customer research.',
    desc: 'Hire digital AI workers that perform B2B prospecting, qualify leads, and handle tier-1 support tickets 24/7.',
    pros: ['Hire pre-built AI agent personas (BDR, Researcher)', 'Connects to email, Slack, and CRM', 'Intuitive dashboard management'],
    cons: ['Requires onboarding for complex custom logic'],
    features: ['Autonomous B2B Sales Agents', 'Multi-Agent Team Delegation', 'Custom Knowledge Grounding'],
  },
  {
    id: 'tool-smythos',
    name: 'SmythOS',
    category: 'Agents',
    pricingType: 'Freemium',
    visits: '2.1M',
    visitsNum: 2100000,
    rating: 4.7,
    url: 'https://smythos.com',
    tagline: 'Operating system for building enterprise autonomous AI agents and complex micro-apps.',
    desc: 'Enterprise platform for creating and hosting autonomous agents with memory, API connectors, and security controls.',
    pros: ['Extensive API connector ecosystem', 'Multi-model LLM routing', 'Enterprise permission controls'],
    cons: ['Interface geared towards technical architects'],
    features: ['Autonomous Agent Operating System', 'Multi-LLM Dynamic Routing', 'Enterprise Role-Based Access Control'],
  },
  {
    id: 'tool-microsoft-autogen',
    name: 'Microsoft AutoGen',
    category: 'Agents',
    pricingType: 'Open Source',
    visits: '6.5M',
    visitsNum: 6500000,
    rating: 4.9,
    url: 'https://microsoft.github.io/autogen',
    tagline: 'Multi-agent conversation framework for building next-generation LLM applications.',
    desc: 'Framework that enables multiple customizable agents to converse, solve problems, and execute code together.',
    pros: ['Industry standard multi-agent conversational framework', 'Code execution in Docker environments', 'Highly flexible conversation patterns'],
    cons: ['Requires Python programming to build'],
    features: ['Multi-Agent Conversational Collaboration', 'Automated Code Execution Sandboxes', 'Human-in-the-Loop Interaction'],
  },
];

async function run() {
  console.log(`Starting Database Seeding for 8 categories x 15 tools = ${TOOLS_CATALOG.length} tools...`);

  const uri = process.env.MONGODB_URI;
  if (!uri) throw new Error('Missing MONGODB_URI in .env');

  const dbName = process.env.MONGODB_DB_NAME || 'toolver_db';
  console.log(`Connecting to MongoDB Atlas database: ${dbName}...`);
  const client = new MongoClient(uri);
  await client.connect();

  const db = client.db(dbName);
  const col = db.collection('tools');

  // Build and insert all 120 tools
  const fullTools = TOOLS_CATALOG.map((t, idx) => {
    const slug = t.slug || t.id.replace('tool-', '');
    return {
      ...t,
      slug,
      logoUrl: `https://toolverai-tool-logos.s3.us-east-1.amazonaws.com/logos/${slug}.png`,
      reviewCount: 1500 + (idx * 317) % 8000,
    isOpenSource: t.pricingType === 'Open Source',
    hasApi: true,
    isFeatured: !!t.isFeatured || idx % 7 === 0,
    isVerified: true,
    monthlyVisits: t.visitsNum,
    monthlyVisitsFormatted: t.visits,
    trafficGrowth: +(15 + (idx * 7.3) % 85).toFixed(1),
    globalRank: idx + 1,
    categoryRank: (idx % 15) + 1,
    topCountries: ['United States (42%)', 'United Kingdom (12%)', 'Germany (8%)'],
    platforms: ['Web', 'Mac', 'Windows'],
    targetAudience: ['Developers', 'Founders', 'Creators', 'Enterprise'],
    upvotes: 2500 + (idx * 481) % 9000,
    keyFeatures: t.features,
    _id: t.id as any,
    trafficStats: {
      monthlyVisits: t.visitsNum,
      monthlyVisitsFormatted: t.visits,
      trafficGrowth: +(15 + (idx * 7.3) % 85).toFixed(1),
      globalRank: idx + 1,
      categoryRank: (idx % 15) + 1,
      topCountry: 'United States (42%)',
      avgDuration: '05:30',
      bounceRate: '29.5%',
    },
    launchedDate: '2023-04-10',
    pricingPlans: [
      {
        id: `${t.id}-starter`,
        name: t.pricingType === 'Paid' ? 'Standard Plan' : 'Free Starter',
        price: t.pricingType === 'Paid' ? '$20' : '$0',
        billingPeriod: 'per month',
        description: `Standard access to ${t.name}.`,
        features: t.features.slice(0, 3),
        ctaText: 'Get Started',
        isPopular: false,
      },
      {
        id: `${t.id}-pro`,
        name: 'Pro Tier',
        price: t.pricingType === 'Paid' ? '$49' : '$25',
        billingPeriod: 'per month',
        description: `Full unlocked features and priority speed for ${t.name}.`,
        features: t.features,
        ctaText: 'Upgrade to Pro',
        isPopular: true,
      },
    ],
    reviews: [
      {
        id: `rev-${t.id}-1`,
        authorName: 'Verified User',
        authorRole: 'Tech Industry Professional',
        authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
        rating: t.rating,
        comment: `Outstanding tool in the ${t.category} space. High reliability and remarkable speed.`,
        date: 'Jan 2026',
        verified: true,
        helpfulCount: 42,
      },
    ],
    createdAt: new Date().toISOString(),
    };
  });

  // Clean old database records and insert all 120 tools
  await col.deleteMany({});
  const insertResult = await col.insertMany(fullTools);
  console.log(`\n✅ Successfully inserted ${insertResult.insertedCount} tools into MongoDB!`);

  // Print category summary
  const breakdown = await col.aggregate([
    { $group: { _id: '$category', count: { $sum: 1 } } },
    { $sort: { count: -1 } },
  ]).toArray();

  console.log('\nFinal Category Breakdown in MongoDB Atlas:');
  breakdown.forEach((b) => {
    console.log(`  ✓ ${b._id}: ${b.count} tools`);
  });

  const totalInDb = await col.countDocuments();
  console.log(`\n🎉 Total Tools Live in Database: ${totalInDb}`);

  await client.close();
}

run().catch((err) => {
  console.error('Seeding Error:', err);
  process.exit(1);
});
